name: Creates a docker image for production

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build the docker image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: redbeard/makecodes
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        env:
          SCOPE: production
        with:
          context: .
          no-cache: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  # deploy:
  #   name: Deploy
  #   runs-on: self-hosted
  #   needs:
  #     - build
  #   steps:
  #     - name: Deploy to production
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         port: ${{ secrets.SSH_PORT }}
  #         script: |
  #           cd /media/data/apps/makecodes-prod
  #           infisical --domain=https://infisical.makecodes.dev/api export --env prod > production.env
  #           docker pull redbeard/makecodes:latest
  #           docker-compose run --rm migration python manage.py migrate
  #           docker-compose run --rm migration python manage.py collectstatic --noinput
  #           docker-compose up -d app0
  #           docker-compose up -d app1
  #           docker-compose up -d worker-integration
  #           docker-compose up -d notebook
  #           docker image prune -f
